### PR TITLE
Add pre-commit hook to lint

### PR DESCRIPTION
**Pull request by bhageena**
Add pre-commit hook using husky to check lint issues

### CODE REVIEW

**Comment by jthomas** [comment]
LGTM.

**Review by joshuaauerbachwatson — APPROVED** [review]
Looks fine.   Before merging, I want to try this through a complete build / install cycle.

**Comment by joshuaauerbachwatson** [comment]
Actually, I don't see a truly meaningful test that can be run without merging and then playing new user.  I will do that and revert if there are problems but I don't think there will be any.

**Comment by joshuaauerbachwatson** [comment]
No problems.

**Pull request merged**
