### PR TITLE
WIP: Adding support for docker property in project.yml

### PR DESCRIPTION
**Pull request by jthomas**
Here is an example of what this would look like:

```yaml
packages:
  - name: default
    actions:
      - name: hello
        main: 'main'
        docker: 'myregistry/actionloop-python-v3.7ai'
```

The code changes were very simple but I've taken the chance to setup unit testing for the deployer code and add this into the build pipeline. Going forward - we'll want to keep adding unit tests for new features. 

**This is a WIP as the [OpenWhisk type for "Exec" ](https://github.com/apache/openwhisk-client-js/blob/7fd311f58c3c50a4f698a69bf8ae4f036cf50f78/lib/main.d.ts#L248-L252) is missing the `main` property. I'm going to fix that upstream so we can merge this. The tests currently have to use a temporary `// @ts-ignore` to build and run locally.** 

In terms of testing - I have run the unit tests for this new feature, run the deployer tests and deployed a sample project using the YAML definition above. All works so far.

### CODE REVIEW

**Comment by jthomas** [comment]
https://github.com/apache/openwhisk-client-js/pull/222

**Comment by jthomas** [comment]
We've now got a new version of the OpenWhisk Client JS available which unblocks this PR BUT the deployer code is now in a separate repo: https://github.com/nimbella/nimbella-deployer.

I'll need to move these changes over there....

**Comment by jthomas** [comment]
This has now been done in https://github.com/nimbella/nimbella-deployer/commit/fb9c21f3cee271cc5e99d19bd9c162c58fcda67b

**Comment by rabbah** [comment]
on nice - might need an example in the docs? i'm not sure how to use it.

**Comment by jthomas** [comment]
https://github.com/nimbella/docs/pull/58

**Pull request closed without merging**
