### PR TITLE
selection prompt for matching namespaces

### PR DESCRIPTION
**Pull request by bhageena**
This change touches the following commands, the change impact area is larger than expected 

1. auth/export
2. auth/logout
3. auth/refresh
4. auth/switch
5. auth/clean
6. namespace/free
7. project/deploy

Behavior prior to this change:
namespace selection prompt comes only if partial namespace name is entered up to the `-`

Behavior after:
namespace selection prompt comes if there are matching namespaces across hosts till the full name is specified and it is unique across available hosts 

relates to #52

Opening for review and discussion.

### CODE REVIEW

**Review by joshuaauerbachwatson — COMMENTED** [review]
Code looks good.   I will test it a bit as part of this review.

**Review by joshuaauerbachwatson — CHANGES_REQUESTED** [review]
The new prompting feature works nicely on commands that I've tried it with and implements the desired new behavior but it is not backward compatible and I think it should be.

It used to be that you needed a trailing hyphen to trigger this "completion" when you had not typed a complete namespace name.   In the new incarnation, the trailing hyphen is not only not needed, it is rejected as an unmatched namespace name.

I realize there is a new possibility, which is that the user did type a complete namespace name but it exists on more than one host.   I agree this should trigger the prompt without there being a trailing dash, because a trailing dash would be artificial.

Because of this, of course, you can't guard the whole logic with a test for the hyphen, and this will complicate the code.  But, I do think we should distinguish the case where the user knows he is abbreviating the namespace from the case where he believes he's provided the whole thing.   I think otherwise (in addition to backward compatibility) we introduce too much opportunity for error.

**Comment by rabbah** [comment]
I have a differing opinion about the `-` but I think the behavior in this PR is confusing for another reason. 

```
> nim auth switch r
...
7: guest on http://localhost:3233
8: whisk.system on http://localhost:3233
```

I don't understand some of the matches like 7 and 8.

If I can drop the `-` I personally will not miss. But the behavior is confusing otherwise in terms of what constitutes a match.

**Comment by bhageena** [comment]
> I don't understand some of the matches like 7 and 8.
 This was not replicable at my end and Rodric suspected it could be a merge issue at his end. In fact, according to implementation only namespace starting with the given input should return. Will recheck if the behavior persists. 
 
Made changes for backward compatibility.

**Comment by rabbah** [comment]
Thanks for checking and also for fixing the backward compatibility. I’ll retest. 

BTW, we discussed in an issue that new prs will start adding their own unit tests.  https://github.com/nimbella/nimbella-cli/issues/50#issuecomment-788136553

**Comment by bhageena** [comment]
> Thanks for checking and also for fixing the backward compatibility. I’ll retest.
> 
> BTW, we discussed in an issue that new prs will start adding their own unit tests. [#50 (comment)](https://github.com/nimbella/nimbella-cli/issues/50#issuecomment-788136553)

sure, there's a level-up, 3-way discussion going on about the existing tests in slack with @joshuaauerbachwatson and @jthomas, adding a new framework and migration will take place soon. will have to do a catch-up then.

**Comment by joshuaauerbachwatson** [comment]
I agree that the most serious backward compatibility problem is fixed.   But, I also think there is a difference of opinion (or emphasis perhaps) between myself and @rabbah about what the continued role should be for the hyphen.   The latest code change follows Rodric's suggestion.  I don't think we should hash out a design issue in the form of competing reviews of a PR.  So, I'm going back to the issue (#52) for this discussion.

**Comment by bhageena** [comment]
Reverting the last commit has necessitated the use of trailing `-` for the prompt (many matches) or an auto-selection (one match) to work, irrespective of `api-host`.

**Review by joshuaauerbachwatson — APPROVED** [review]
I did not re-review code but I did retest behavior.   It seems to be behaving as we wish and reliably so (I have lots of API hosts and namespaces so I was able to give it a workout).

So, LTGM.

**Pull request merged**
